#!/usr/bin/env node
const { program } = require('commander');
const main = require('../lib/main.js');
const open = require('open');

program
  .version(require('../package').version)
  .usage('[entry]')
  .option('-p, --port [port]', 'Type port !')
  .option('-o, --open [--open]', 'Auto open default browser')
  .option('-v, --version [--version]', 'The pack version')
  .option('-a, --allowOrigin [--allowOrigin]', 'Allow-Origin *')
  .option('-h, --history [history]', 'Type -h enable history mode !')
  .parse(process.argv);

const options = program.opts();

options.port = (options.port > 0 && options.port != true) ? options.port : 8080;
// 监测端口是否被占用
main.checkPort(options.port).then(() => {
  main.createServer(options);
  if (options.open) {
    open(`http://localhost:${options.port}`);
  }
}).catch((err) => {
  console.log(new Error(err));
});
